---
title: Text Matching
author: Ezra Citron
date: '2021-07-23'
slug: []
categories: []
tags: []
description: ~
featured_image: ~
---

One problem I often come across in my work and I also stumbles into a my recent blog about [harry potter film sales]() was, I have two lists of words, 1 with words that I actually have, and one that words that i'd like them to be, the task in to map the first onto the second. 

Let me make this more concrete. 

### Example

### Levenstine distance
The levenstine distance is a fancy way of saying "how different are the letters in these 2 words". The word 'getting' and 'greeting' are pretty similar. All you have to do is add an 'r' and change a 't' to an 'e' and they are the same word. Levenstine distance counts the number of insertions, deletions and letter swaps to get from one word to another, and this is thier levenstine distance. 

The `adist` function from the `utils` package which comes built in with R will do this for you.

```{r}
adist('getting','greeting')
```

We had to add an 'r' and change 't' to 'e' to get from the first to the second. 

